// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWtsm3edZtzwz6OEvPsH9y9hwFzctku4c',
    appId: '1:351864923845:web:20c62d04925ae90be372ac',
    messagingSenderId: '351864923845',
    projectId: 'fir-flutter-codelab-f7f02',
    authDomain: 'fir-flutter-codelab-f7f02.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-f7f02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1cT0dPXU03UpptsjiFUWS2xbEw-cPOFg',
    appId: '1:351864923845:android:03d7744caef9f7eee372ac',
    messagingSenderId: '351864923845',
    projectId: 'fir-flutter-codelab-f7f02',
    storageBucket: 'fir-flutter-codelab-f7f02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3wiVzUTYA9xGWAoDHAiz_DU-QHKbYgyc',
    appId: '1:351864923845:ios:b4bf704bca96efd7e372ac',
    messagingSenderId: '351864923845',
    projectId: 'fir-flutter-codelab-f7f02',
    storageBucket: 'fir-flutter-codelab-f7f02.appspot.com',
    iosClientId: '351864923845-ooccvushuq48f3oic4ogq5ebp8f9v8p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3wiVzUTYA9xGWAoDHAiz_DU-QHKbYgyc',
    appId: '1:351864923845:ios:b4bf704bca96efd7e372ac',
    messagingSenderId: '351864923845',
    projectId: 'fir-flutter-codelab-f7f02',
    storageBucket: 'fir-flutter-codelab-f7f02.appspot.com',
    iosClientId: '351864923845-ooccvushuq48f3oic4ogq5ebp8f9v8p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDelivery',
  );
}
